services:
  postgres:
    image: postgres:17
    container_name: user-app-postgres
    environment:
      POSTGRES_DB: user_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_app_postgres_data:/var/lib/postgresql/data

volumes:
  user_app_postgres_data: